---
## --------------
## レンタルサーバーのログインパスワード
## --------------
sakura_login_password: "{{ lookup('env', 'SAKURA_LOGIN_PASSWORD') }}"

## --------------
## ダウンロードするWordPressのデフォルトのロケール
## --------------
wp_default_locale: ja

## --------------
## インストールするLeantimeのバージョン
## --------------
leantime_version: latest

## --------------
## Leantimeの設定
## --------------
leantime_env:
  LEAN_DEBUG: 0
  LEAN_DB_HOST: "{{ lookup('env', 'LEAN_DB_HOST') | default('localhost', true) }}"
  LEAN_DB_DATABASE: "{{ lookup('env', 'LEAN_DB_DATABASE') }}"
  LEAN_DB_USER: "{{ lookup('env', 'LEAN_DB_USER') }}"
  LEAN_DB_PASSWORD: "{{ lookup('env', 'LEAN_DB_PASSWORD') }}"
  LEAN_LANGUAGE: ja-JP
  LEAN_DEFAULT_TIMEZONE: Asia/Tokyo
  # LEAN_SESSION_PASSWORD: "{{ lookup('env', 'LEAN_SESSION_PASSWORD') }}"

## --------------
## Leantime初期インストール時に登録するアカウント
## --------------
leantime_initial_account:
  admin_email: postmaster@{{ inventory_hostname }}
  admin_password: password
  company_name: 山田商店
  first_name: 山田
  last_name: 太郎

## --------------
## leantime用cronジョブ
## --------------
# leantime_cron_jobs:
#   - name: "Backs up database"
#     command: >
#       cd ~/www/leantime
#       &&
#       ./bin/leantime db:backup
#     hour: 06
#     minute: 30
#   - name: "Delete the cached mutex files created by scheduler"
#     command: >
#       cd ~/www/leantime
#       &&
#       ./bin/leantime schedule:clear-cache
#     minute: 15
#   - name: "Run the scheduled commands"
#     command: >
#       cd ~/www/leantime
#       &&
#       ./bin/leantime schedule:run
