---
- name: Setup Sakura Rental Server
  hosts: all
  gather_facts: false
  become: false
  pre_tasks:
    - name: 必須の変数が定義済みかどうかのチェック
      ansible.builtin.assert:
        that:
          - sakura_login_password is defined
          - sakura_login_password | length > 0
        fail_msg: "レンタルサーバーのログインパスワードが未設定です"
        quiet: true
  tasks:
    - name: binディレクトリを作成
      ansible.builtin.file:
        path: "{{ home_dir }}/bin"
        state: directory
        mode: "0755"
    - name: tmpディレクトリを作成
      ansible.builtin.file:
        path: "{{ home_dir }}/tmp"
        state: directory
        mode: "0755"
    - name: PHPのセットアップ
      ansible.builtin.import_tasks:
        file: tasks/php.yml
      tags: php
    - name: Composerのインストール
      ansible.builtin.import_tasks:
        file: tasks/composer.yml
      tags: composer
    - name: WP-CLIのセットアップ
      ansible.builtin.import_tasks:
        file: tasks/wp-cli.yml
      tags:
        - wp
        - wp-cli
        - wp_cli
    - name: bashのセットアップ
      ansible.builtin.import_tasks:
        file: tasks/bash.yml
      tags: bash
    - name: pipのインストール
      ansible.builtin.import_tasks:
        file: tasks/pip.yml
      tags: pip
    - name: ログインシェルをbashに変更
      ansible.builtin.import_tasks:
        file: tasks/login-shell.yml
      tags:
        - shell
        - login-shell
        - login_shell
    - name: git prompt for bashのインストール
      ansible.builtin.import_tasks:
        file: tasks/git-prompt.yml
      tags:
        - git
        - prompt
        - git-prompt
        - git_prompt
    - name: MySQL接続設定ファイルの生成
      ansible.builtin.import_tasks:
        file: tasks/mysql.yml
      tags: mysql
    - name: rcloneのインストール
      ansible.builtin.import_tasks:
        file: tasks/rclone.yml
      tags:
        - rclone
        - backup
    - name: Resticのインストール
      ansible.builtin.import_tasks:
        file: tasks/restic.yml
      tags:
        - restic
        - backup
    - name: nodebrewのインストール
      ansible.builtin.import_tasks:
        file: tasks/nodebrew.yml
      tags:
        - nodebrew
        - nodejs
    - name: goのインストール
      ansible.builtin.import_tasks:
        file: tasks/golang.yml
      tags:
        - go
        - golang
    - name: rustのインストール
      ansible.builtin.import_tasks:
        file: tasks/rust.yml
      tags: rust
    - name: ezaのインストール
      ansible.builtin.import_tasks:
        file: tasks/eza.yml
      tags: eza
    - name: lazygitのインストール
      ansible.builtin.import_tasks:
        file: tasks/lazygit.yml
      tags: lazygit
    - name: バックアップ設定
      ansible.builtin.import_tasks:
        file: tasks/backup.yml
      tags: backup
    # - name: mkdocsのインストール
    #   ansible.builtin.import_tasks:
    #     file: tasks/mkdocs.yml
    #   tags: mkdocs
    # - name: leantimeのインストール
    #   ansible.builtin.import_tasks:
    #     file: tasks/leantime.yml
    #   tags: leantime
    # - name: Node.jsのコンパイル
    #   ansible.builtin.command:
    #     cmd: nice -n 20 {{ home_dir }}/.nodebrew/current/bin/nodebrew compile stable
    #     creates: "{{ home_dir }}/.nodebrew/current/bin/node"
    #   tags: nodejs
