---
- name: Create/update ~/.bash_profile
  ansible.builtin.blockinfile:
    path: "{{ home_dir }}/.bash_profile"
    marker: "# {mark} bash ANSIBLE MANAGED BLOCK"
    content: |
      export LANG=ja_JP.UTF-8
      export PATH=$HOME/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
      export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
      if [ -f ~/.bashrc ]; then
          . ~/.bashrc
      fi
    mode: "0644"
    create: true
- name: Create/update ~/.bashrc
  ansible.builtin.blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} bash ANSIBLE MANAGED BLOCK"
    content: |
      if [ -f ~/.secret ]; then
          . ~/.secret
      fi
    mode: "0644"
    create: true
- name: Create/update ~/.secret
  ansible.builtin.blockinfile:
    path: ~/.secret
    marker: "# {mark} bash ANSIBLE MANAGED BLOCK"
    content: |
      {% for secret_env_name, secret_env_value in (secret_env | default({})).items() -%}
      export {{ secret_env_name }}="{{ secret_env_value }}"
      {% endfor %}
    mode: "0600"
    create: true
- name: Set ls command alias
  ansible.builtin.lineinfile:
    path: "{{ home_dir }}/.bashrc"
    regexp: ^alias {{ item.alias }}=
    line: alias {{ item.alias }}="{{ item.value }}"
  loop:
    - alias: ls
      value: ls --color=auto
    - alias: ll
      value: ls -l
    - alias: la
      value: ls -A
