---
- name: Check cargo command
  ansible.builtin.stat:
    path: "{{ home_dir }}/.cargo/bin/cargo"
  register: cargo_result
- name: rustのインストール
  ansible.builtin.import_tasks:
    file: rust.yml
  when: not cargo_result.stat.exists
- name: Install eza
  ansible.builtin.command:
    cmd: nice -n 20 ~/.cargo/bin/cargo install eza
    chdir: "{{ home_dir }}"
  environment:
    CARGO_TARGET_DIR: "{{ home_dir }}/tmp"
- name: Set ls command alias
  ansible.builtin.lineinfile:
    path: "{{ home_dir }}/.bashrc"
    regexp: ^alias {{ item.alias }}=
    line: alias {{ item.alias }}="{{ item.value }}"
  loop:
    - alias: ls
      value: eza --git --header
    - alias: ll
      value: ls -l
    - alias: la
      value: ls -a
