---
- name: Get rclone latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    headers:
      Accept: application/vnd.github+json
  register: latest_releases
- name: Set version variable
  ansible.builtin.set_fact:
    lazygit_version: "{{ latest_releases.json.tag_name }}"
- name: Download release archive
  ansible.builtin.get_url:
    url: https://github.com/jesseduffield/lazygit/releases/download/{{ lazygit_version }}/lazygit_{{ lazygit_version[1:] }}_freebsd_x86_64.tar.gz
    dest: "{{ home_dir }}/tmp/lazygit_{{ lazygit_version[1:] }}_freebsd_x86_64.tar.gz"
    mode: "0644"
  register: download_result
- name: Unarchive lazygit current release archive
  ansible.builtin.command:
    cmd: tar vxfz lazygit_{{ lazygit_version[1:] }}_freebsd_x86_64.tar.gz --include=lazygit -C "{{ home_dir }}/bin"
    chdir: "{{ home_dir }}/tmp"
  when: download_result is changed
- name: Find cleanup directories
  ansible.builtin.find:
    paths:
      - "{{ home_dir }}/tmp"
    file_type: directory
    patterns:
      - lazygit_*_freebsd_x86_64.tar.gz
    excludes:
      - lazygit_{{ lazygit_version[1:] }}_freebsd_x86_64.tar.gz
  register: find_result
- name: Cleanup directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_result.files }}"
  loop_control:
    label: "{{ item.path }}"
