---
- name: Set Install version variable
  when: leantime_version == 'latest'
  block:
    - name: Get leantime latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/Leantime/leantime/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        leantime_version: "{{ latest_releases.json.tag_name }}"
- name: Install/Update Leantime
  ansible.builtin.unarchive:
    src: https://github.com/Leantime/leantime/releases/download/{{ leantime_version }}/Leantime-{{ leantime_version }}.zip
    dest: "{{ home_dir }}/www"
    remote_src: true
- name: Replace Apache option
  ansible.builtin.replace:
    path: "{{ home_dir }}/www/leantime/public/.htaccess"
    regexp: FollowSymLinks
    replace: SymLinksIfOwnerMatch
- name: Change parmission(cli script file)
  ansible.builtin.file:
    path: "{{ home_dir }}/www/leantime/bin/leantime"
    mode: "0755"
- name: Change parmission(directories)
  ansible.builtin.file:
    path: "{{ home_dir }}/www/leantime/{{ item }}"
    mode: "0777"
  loop:
    - cache
    - cache/avatars
    - cache/views
    - userfiles
    - public/userfiles
- name: Check .env file
  ansible.builtin.stat:
    path: "{{ home_dir }}/www/leantime/config/.env"
  register: dotenv_stat_result
- name: Copy default .env file
  ansible.builtin.copy:
    src: "{{ home_dir }}/www/leantime/config/sample.env"
    dest: "{{ home_dir }}/www/leantime/config/.env"
    mode: "0644"
    remote_src: true
  when: not dotenv_stat_result.stat.exists
  register: generate_dotenv
- name: Update .env file
  ansible.builtin.lineinfile:
    path: "{{ home_dir }}/www/leantime/config/.env"
    regexp: ^{{ item.key }}\s*=
    line: "{{ item.key }} = {{ \"'\" + item.value + \"'\" if item.value is string else item.value }}"
  loop: "{{ leantime_env | default({}) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
- name: Execute database migration
  ansible.builtin.command:
    cmd: >
      ./bin/leantime db:migrate
      {% if generate_dotenv is changed -%}
      --email={{ leantime_initial_account.admin_email }}
      --password={{ leantime_initial_account.admin_password }}
      --company-name={{ leantime_initial_account.company_name }}
      --first-name={{ leantime_initial_account.first_name }}
      --last-name={{ leantime_initial_account.last_name }}
      {% endif %}
    chdir: "{{ home_dir }}/www/leantime"
