---
- name: Install pexpect
  ansible.builtin.pip:
    name: pexpect
    executable: ~/.local/bin/pip
    extra_args: --user
- name: Cheange login shell
  ansible.builtin.expect:
    command: chsh -s /usr/local/bin/bash
    responses:
      (?i)password: "{{ sakura_login_password }}"
