---
- name: Check cargo command
  ansible.builtin.stat:
    path: "{{ home_dir }}/.cargo/bin/cargo"
  register: cargo_result
- name: rustのインストール
  ansible.builtin.import_tasks:
    file: rust.yml
  when: not cargo_result.stat.exists
- name: Install pagefind
  ansible.builtin.command:
    cmd: nice -n 20 {{ home_dir }}/.cargo/bin/cargo install pagefind
    chdir: "{{ home_dir }}"
  environment:
    CARGO_TARGET_DIR: "{{ home_dir }}/tmp"
