---
- name: Get rclone latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/rclone/rclone/releases/latest
    headers:
      Accept: application/vnd.github+json
  register: latest_releases
- name: Set version variable
  ansible.builtin.set_fact:
    rclone_version: "{{ latest_releases.json.tag_name }}"
- name: Unarchive rclone current release archive
  ansible.builtin.unarchive:
    src: https://github.com/rclone/rclone/releases/download/{{ rclone_version }}/rclone-{{ rclone_version }}-freebsd-amd64.zip
    dest: ~/bin
    include:
      - rclone-{{ rclone_version }}-freebsd-amd64/rclone
    remote_src: true
    extra_opts:
      - "-j"
      - "-o"
