---
- name: Get rclone latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/rclone/rclone/releases/latest
    headers:
      Accept: application/vnd.github+json
  register: latest_releases
- name: Set version variable
  ansible.builtin.set_fact:
    rclone_version: "{{ latest_releases.json.tag_name }}"
- name: Unarchive rclone current release archive
  ansible.builtin.unarchive:
    src: https://github.com/rclone/rclone/releases/download/{{ rclone_version }}/rclone-{{ rclone_version }}-freebsd-amd64.zip
    dest: ~/bin
    remote_src: true
    extra_opts:
      - "-a"
- name: Create rclone symlink
  ansible.builtin.file:
    path: ~/bin/rclone
    src: ~/bin/rclone-{{ rclone_version }}-freebsd-amd64/rclone
    state: link
    mode: "0755"
- name: Find cleanup directories
  ansible.builtin.find:
    paths:
      - ~/bin
    file_type: directory
    patterns:
      - rclone-v*-freebsd-amd64
    excludes:
      - rclone-{{ rclone_version }}-freebsd-amd64
  register: find_result
- name: Cleanup directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_result.files }}"
  loop_control:
    label: "{{ item.path }}"
