---
- name: Check installed restic
  ansible.builtin.stat:
    path: "{{ home_dir }}/bin/restic"
  register: restic_result
- name: Install rclone
  when: not restic_result.stat.exists
  block:
    - name: Get restic latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/restic/restic/releases/latest
        headers:
          Accept: application/vnd.github+json
      register: latest_release
    - name: Set version variable
      ansible.builtin.set_fact:
        restic_version: "{{ latest_release.json.tag_name }}"
    - name: Download restic archive file
      ansible.builtin.get_url:
        url: https://github.com/restic/restic/releases/download/{{ restic_version }}/restic_{{ restic_version[1:] }}_freebsd_amd64.bz2
        dest: "{{ home_dir }}/bin/restic.bz2"
        mode: "0644"
    - name: Unarchive restic current release archive
      ansible.builtin.command:
        cmd: bunzip2 {{ home_dir }}/bin/restic.bz2
        chdir: "{{ home_dir }}/bin"
    - name: Set parmission
      ansible.builtin.file:
        path: "{{ home_dir }}/bin/restic"
        mode: "0755"
- name: Update restic
  ansible.builtin.command:
    cmd: "{{ home_dir }}/bin/restic self-update"
    chdir: "{{ home_dir }}"
  changed_when: false
