---
- name: Create website directory
  ansible.builtin.file:
    path: ~/www/{{ item.url }}
    state: directory
    mode: "0755"
  loop: "{{ websites | default([]) }}"
  loop_control:
    label: "{{ item.name | default(item.url) }}"
- name: Create alias
  ansible.builtin.file:
    path: ~/www/{{ item.alias }}
    src: "{{ item.url }}"
    state: link
  loop: "{{ websites | default([]) | selectattr('alias', 'defined') | list }}"
  loop_control:
    label: "{{ item.name | default(item.url) }}"
